# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9e181902-42f2-4b99-bc78-4a8046a00c04";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1806-14A0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/sda" =
    { device = "/dev/disk/by-uuid/c5284447-0e1a-4a6d-8bd7-1e5e0d42ac0d";
      fsType = "ext4";
    };

  fileSystems."/mnt/sdc" =
    { device = "/dev/disk/by-uuid/db601999-ddc2-454e-b741-b61d88570a36";
      fsType = "ext4";
    };

  fileSystems."/mnt/sdb" =
    { device = "/dev/disk/by-uuid/93c21925-0b3c-49ff-9016-bdb73e3f610f";
      fsType = "ext4";
    };

  fileSystems."/mnt/sdd" =
    { device = "/dev/disk/by-uuid/ed5dda73-0f3a-41e2-9569-2825c612320e";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
